
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: !secret http_url
#  ssl_certificate: /config/ssl/fullchain.pem
#  ssl_key: /config/ssl/privkey.pem

recorder:
  db_url: !secret mysql_host

# teste comments do aurelio
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - 611383381

notify:
  - name: AURELIO
    platform: telegram
    chat_id: 611383381

cloud:
  alexa:
    filter:
      include_entities:
        - light.luzes_da_tv_da_sala

alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.com

ifttt:
  key: !secret ifttt_token

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 55

media_player:
#  - platform: alexa
#    email: !secret alexa_email
#    password: !secret alexa_pass
#    url: amazon.com
  - platform: androidtv
    name: Amazon Fire TV
    host: 192.168.68.117
    device_class: firetv
    adbkey: "/config/.android/adbkey"
    apps:
      com.amazon.amazonvideo.livingroom: "Amazon Video"
      com.netflix.ninja: "Netflix"
      com.google.android.youtube.tv: "YouTube"
      com.google.android.tvlauncher: "Menu"
    state_detection_rules:
      'com.amazon.amazonvideo.livingroom.firetv':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.amazon.tv.launcher':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.netflix.ninja':
        - 'media_session_state'

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named script
scene: !include scenes.yaml
frontend: !include frontend.yaml
lovelace: !include lovelace.yaml
light: !include light.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
