
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://aureliosaraiva.duckdns.org:9877
#  ssl_certificate: /config/ssl/fullchain.pem
#  ssl_key: /config/ssl/privkey.pem


recorder:
  db_url: mysql://homeassistant:Z4vMkyltu@192.168.68.110/homeassistant?charset=utf8

lovelace:
  mode: yaml

# teste comments do aurelio
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml

sensor:
   - platform: template
     sensors:
       sensor_count:
         entity_id: []
         friendly_name: 'Número de Sensores'
         value_template: '{{ states.sensor | count }}'

       automation_count:
         entity_id: []
         friendly_name: 'Número de Automações'
         value_template: '{{ states.automation | count }}'

       script_count:
         entity_id: []
         friendly_name: 'Número de Scripts'
         value_template: '{{ states.script | count }}'

       switch_count:
         entity_id: []
         friendly_name: 'Número de Switches'
         value_template: '{{ states.switch | count }}'

       binary_sensor_count:
         entity_id: []
         friendly_name: 'Número de Sensor Binário'
         value_template: '{{ states.binary_sensor | count }}'

       lights_count:
         entity_id: []
         friendly_name: 'Número de Luzes'
         value_template: '{{ states.light | count }}'

       tracker_count:
         entity_id: []
         friendly_name: 'Número de Devices'
         value_template: '{{ states.device_tracker | count }}'

       zwave_count:
         entity_id: []
         friendly_name: 'Zwave Devices'
         value_template: '{{ states.zwave_count | count }}'

       media_player_count:
         entity_id: []
         friendly_name: 'Multimidia'
         value_template: '{{ states.media_player | count }}'
