- platform: group
  name: lamps_living_room_sofa
  entities:
    - light.lamp_living_room_sofa_1_light
    - light.lamp_living_room_sofa_2_light
    - light.lamp_living_room_sofa_3_light
    - light.lamp_living_room_sofa_4_light

- platform: group
  name: lamps_living_room_window
  entities:
    - light.lamp_living_room_window_1_light
    - light.lamp_living_room_window_2_light

- platform: group
  name: lamps_living_room_tv
  entities:
    - light.lamp_living_room_tv_1_light
    - light.lamp_living_room_tv_2_light
    - light.lamp_living_room_tv_3_light

- platform: group
  name: lamps_living_room_tv_side
  entities:
    - light.lamp_living_room_tv_4_light
    - light.lamp_living_room_tv_5_light

- platform: group
  name: lamps_living_room_garden
  entities:
    - light.lamp_living_room_garden_1_light
    - light.lamp_living_room_garden_2_light
    - light.lamp_living_room_garden_3_light

- platform: group
  name: lamps_bedroom
  entities:
    - light.lamp_bedroom_left_light
    - light.lamp_bedroom_right_light
