- platform: template
  sensors:
    sensor_count:
      entity_id: []
      friendly_name: 'Número de luz acesa do sofá'
      value_template: >
        {{ states.light.luz_sofa | count == states.light.luz_sofa | selectattr('state','eq', 'on') | list | count }}

    sensor_count:
      entity_id: []
      friendly_name: 'Número de Sensores'
      value_template: '{{ states.sensor | count }}'

    automation_count:
      entity_id: []
      friendly_name: 'Número de Automações'
      value_template: '{{ states.automation | count }}'

    script_count:
      entity_id: []
      friendly_name: 'Número de Scripts'
      value_template: '{{ states.script | count }}'

    switch_count:
      entity_id: []
      friendly_name: 'Número de Switches'
      value_template: '{{ states.switch | count }}'

    binary_sensor_count:
      entity_id: []
      friendly_name: 'Número de Sensor Binário'
      value_template: '{{ states.binary_sensor | count }}'

    lights_count:
      entity_id: []
      friendly_name: 'Número de Luzes'
      value_template: '{{ states.light | count }}'

    tracker_count:
      entity_id: []
      friendly_name: 'Número de Devices'
      value_template: '{{ states.device_tracker | count }}'

    zwave_count:
      entity_id: []
      friendly_name: 'Zwave Devices'
      value_template: '{{ states.zwave_count | count }}'

    media_player_count:
      entity_id: []
      friendly_name: 'Multimidia'
      value_template: '{{ states.media_player | count }}'

    presence_home:
      friendly_name: Tem alguém em casa
      entity_id:
        - binary_sensor.aurelio_saraiva_s_galaxy_a8_2018_presence
        - binary_sensor.camila_medrosa_ferreira_s_galaxy_s9_presence
      value_template: >-
        {% if is_state('binary_sensor.camila_medrosa_ferreira_s_galaxy_s9_presence', 'on')
           or is_state('binary_sensor.aurelio_saraiva_s_galaxy_a8_2018_presence', 'on') %}
           Sim
        {% else %}
           Não
        {% endif %}
    average_house_temp:
      friendly_name: 'Temperatura média da casa'
      unit_of_measurement: "°C"
      value_template: >-
        {{
          float(
          float(states.sensor.temperatura_quarto.state) +
          float(states.sensor.temperature_lavanderia.state) +
          float(states.sensor.porta_da_frente_temperature_measurement.state)
          ) / 3 | round(1)
        }}
