title: Casa da Lara&Mia
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    cards: !include lovelace/home.yaml
  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards: !include lovelace/weather.yaml
  - icon: mdi:play-circle-outline
    id: media
    title: Media
    cards: !include lovelace/media.yaml
  - icon: mdi:settings
    id: settings
    title: Settings
    cards: !include lovelace/settings.yaml
  - icon: mdi:information-variant
    id: information-variant
    title: HA
    cards: !include lovelace/ha.yaml
  - icon: mdi:test-tube
    id: test
    title: Testing
    cards: !include lovelace/lab.yaml
