- type: entities
  title: Dispositivos
  show_header_toggle: false
  entities:
    - entity: sensor.media_player_count
      icon: mdi:cast
      name: Multimidia
    - entity: sensor.tracker_count
      icon: mdi:cellphone-link
      name: Total de Tracker
    - entity: sensor.lights_count
      icon: mdi:lightbulb
    - entity: sensor.binary_sensor_count
      icon: mdi:nintendo-switch
    - entity: sensor.switch_count
      icon: mdi:toggle-switch
    - entity: sensor.automation_count
      icon: mdi:home-assistant
    - entity: sensor.script_count
      icon: mdi:script-text-outline
    - entity: sensor.sensor_count
      icon: mdi:gauge
- type: entities
  entities:
    - entity: input_boolean.zigbee_permit_join
    - entity: timer.zigbee_permit_join
    - entity: sensor.bridge_state
  show_header_toggle: false
  title: Zigbee
- type: entities
  title: Bateria
  show_header_toggle: false
  entities:
    - sensor.door_garden_battery
    - sensor.door_kitchen_battery
    - sensor.door_laboratory_battery
    - sensor.door_main_battery
    - sensor.door_bathroom_social_battery
    - sensor.door_laundry_battery
    - type: divider
    - sensor.motion_external_door_battery
    - sensor.motion_garden_battery
    - sensor.motion_kitchen_battery
    - sensor.motion_laboratory_battery
    - sensor.motion_bedroom_battery
    - sensor.motion_garden_laundry_battery
    - sensor.motion_office_battery
    - sensor.motion_stair_battery
    - type: divider
    - sensor.temperature_bedroom_battery
    - sensor.temperature_bathroom_battery
    - sensor.temperature_laboratory_battery
    - sensor.temperature_livingroom_battery
    - sensor.temperature_office_battery
    - type: divider
    - sensor.lux_living_room_battery
    - sensor.adega_battery

- type: horizontal-stack
  cards:
  - type: sensor
    name: CPU Temperature
    icon: mdi:memory
    entity: sensor.cpu_temperature
    hours_to_show: 24
    graph: line
    detail: 1
    theme: midnightclear
  - type: sensor
    name: Disk use
    icon: mdi:harddisk
    entity: sensor.disk_use_percent_home
    hours_to_show: 24
    graph: line
    detail: 1
    theme: midnightclear
- type: horizontal-stack
  cards:
    - type: sensor
      entity: sensor.processor_use
      name: Processor
      hours_to_show: 24
      graph: line
      detail: 1
      theme: midnightclear
    - type: sensor
      entity: sensor.memory_use_percent
      name: Memory
      hours_to_show: 24
      graph: line
      detail: 1
      theme: midnightclear
