- id: good_moring_kitchen
  alias: Morning
  initial_state: off
  trigger:
    - entity_id: binary_sensor.sensor_de_movimento_cozinha_motion
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.morning.attributes.last_triggered | default(0)) | int > 21600)}}'
  action:
    - service: script.speech_engine
      data_template:
        media_player: media_player.echo_dot_cozinha
        call_no_announcement: 0
