- alias: when_neide_comes_home

  trigger:
    - platform: state
      entity_id:
        - binary_sensor.door_main_contact
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '7:30:00'
        before: '9:30:00'
        weekday:
          - thu
      - condition: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.when_neide_comes_home.attributes.last_triggered | default(0)) | int > 36000)}}'
  action:
    - service: script.speech_engine
      data_template:
        media_player: media_player.echo_de_aurelio
        custom_message: >
          <p>Bom dia Neide. Seja bem vinda a casa mais inteligente do condomínio.</p>
          <p>Tenha um ótimo dia.</p>
        call_no_random: 1
        call_no_announcement: 1
