- id: network_new_device_detected
  alias: network_new_device_detected
  trigger:
  - event_data:
      action: network_new_device
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
    - service: script.speech_engine
      data_template:
        media_player: media_player.alexa_laboratory
        custom_message: >
          {{ [
           "Foi detectado um novo dispositivo na rede.",
           "Detectei um novo dispositivo.",
           "Novo dispositivo detectado e configurado."
           ] | random }}
