##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'People Greeting'

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          "outro conteudo de teste personalizado"
        call_responsibilities: 1
        call_no_announcement: 0
        call_garage_check: 1
        call_window_check: 1

- alias: 'Test button'
  trigger:
    - platform: state
      entity_id: 0xbc33acfffe616a3c_action
      to: '4_single'
  action:
    - service: switch.toggle
      entity_id: switch.lamp_laboratory_switch
