- id: turn_on_the_light_when_is_sunset
  alias: turn_on_the_light_when_is_sunset
  description: Acende as luzes
  trigger:
    - event: sunset
      platform: sun
      offset: "-01:00:00"
  condition:
    - condition: time
      after: '16:00:00'
      before: '18:30:00'
  action:
    - service: notify.alexa_media
      data:
        target:
          - media_player.echo_dot_de_aurelio
        data:
          type: announce
        message: >
           {{ [
            "O sol vai se pôr em 1 hora, vou acender algumas luzes.",
            "Está começando a escurecer, vou acender algumas luzes."
            ] | random }}
    - delay: '10'
    - service: scene.turn_on
      entity_id: scene.light_sun_set
