- id: update_notification
  alias: Update Home Assistant
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.AURELIO
      data:
        message: 'There is a new Home Assistant release available.'
    - service: script.speech_engine
      data_template:
        custom_message: >
          {{ [
           "Meus criadores informaram que existe atualizações para minha programação.",
           "Tenho uma nova atualização para meu sistema.",
           "Uma nova atualização foi disponibilizada para meu sistema.",
           "Recebi o aviso que tenho uma nova atualização."
           ] | random }}
