
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: !secret http_url
#  ssl_certificate: /config/ssl/fullchain.pem
#  ssl_key: /config/ssl/privkey.pem

recorder:
  db_url: !secret mysql_host

# teste comments do aurelio
# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: 192.168.68.109
  discovery: true

webhook:
circadian_lighting:

zigbee2mqtt_networkmap:
#topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
   title: 'Zigbee Map'
   url: '/local/community/zigbee2mqtt_networkmap/map.html'
   icon: 'mdi:graphql'
  esphome:
    title: 'ESPHome'
    url: 'http://192.168.68.109:6052/'
    icon: 'mdi:memory'


homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - 611383381

notify:
  - name: AURELIO
    platform: telegram
    chat_id: 611383381

cloud:
  alexa:
    filter:
      include_entities:
        - light.lamps_bedroom
        - light.lamp_bedroom_left_light
        - light.lamp_bedroom_right_light
        - light.lamps_living_room_tv
        - light.lamps_living_room_sofa
        - light.lamps_living_room_window
        - sensor.temperature_bedroom_temperature
        - switch.lamp_laboratory
        - switch.lamp_laboratory_switch
    entity_config:
      light.lamps_bedroom:
        name: Luzes do quarto
        description: Luzes do quarto
        display_categories: LIGHT
      light.lamp_bedroom_left_light:
        name: Abjur da Camila
        description: Luz do abjur da Camila
        display_categories: LIGHT
      light.lamp_bedroom_right_light:
        name: Abjur do Aurelio
        description: Luz do abjur do Aurelio
        display_categories: LIGHT
      light.lamps_living_room_tv:
        name: Luzes da TV
        description: Luzes da televisão da sala
        display_categories: LIGHT
      light.lamps_living_room_sofa:
        name: Luzes do sofá
        description: Luzes do sofá
        display_categories: LIGHT
      light.lamps_living_room_window:
        name: Luzes da janela
        description: Luzes da janela
        display_categories: LIGHT
      sensor.temperature_bedroom_temperature:
        name: Temperatura do quarto
        description: Temperatura do quarto
        display_categories: TEMPERATURE_SENSOR
      switch.lamp_laboratory:
        name: Luz do laboratório
        description: Luz do laboratório
        display_categories: LIGHT
      switch.lamp_laboratory_switch:
        name: Luminária
        description: Luminária
        display_categories: LIGHT





alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.com

ifttt:
  key: !secret ifttt_token

media_player:
#  - platform: alexa
#    email: !secret alexa_email
#    password: !secret alexa_pass
#    url: amazon.com
  - platform: androidtv
    name: Amazon Fire TV
    host: 192.168.68.117
    device_class: firetv
    adbkey: "/config/.android/adbkey"
    apps:
      com.amazon.amazonvideo.livingroom: "Amazon Video"
      com.netflix.ninja: "Netflix"
      com.google.android.youtube.tv: "YouTube"
      com.google.android.tvlauncher: "Menu"
    state_detection_rules:
      'com.amazon.amazonvideo.livingroom.firetv':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.amazon.tv.launcher':
        - 'playing':
            'wake_lock_size': 4  # this indentation is important!
        - 'playing':
            'wake_lock_size': 3  # this indentation is important!
        - 'paused':
            'wake_lock_size': 2  # this indentation is important!
        - 'paused':
            'wake_lock_size': 1  # this indentation is important!
        - 'standby'
      'com.netflix.ninja':
        - 'media_session_state'

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named script
scene: !include scenes.yaml
frontend: !include frontend.yaml
lovelace: !include lovelace.yaml
light: !include light.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml

camera:
  - platform: generic
    name: ISS
    still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }}&zoom=4&size=865x512&maptype=mapnik&markers={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }},lightblue
    limit_refetch_to_url_change: true

timer:
  zigbee_permit_join:
    name: Tempo restante
    duration: 600

input_text:
  text1:
    name: manual_message
    initial: 'Enter your text here'

input_select:
  message_target:
    name: 'My broadcast message'
    options:
      - "media_player.alexa_kitchen"
      - "media_player.alexa_living_room"
      - "media_player.alexa_laboratory"
      - "media_player.alexa_office"
      - "media_player.alexa_bedroom"
      - "media_player.alexa_garden"
      - "media_player.todo_lugar"
    initial: "media_player.alexa_living_room"
    icon: mdi:speaker-wireless
  watt_card:
    name: Watt Hours
    options:
      - 24
      - 12
      - 4
      - 2
      - 1
      - 48
      - 72
    initial: 24
    icon: mdi:flash

utility_meter:
  washing_machine_year_energy:
    source: sensor.washing_machine_total_daily_energy
    cycle: yearly
    tariffs:
      - peak
  washing_machine_month_energy:
    source: sensor.washing_machine_total_daily_energy
    cycle: monthly
    tariffs:
      - peak
