family:
  entities:
    - device_tracker.life360_aurelio_saraiva


external_doors:
  entities:
    - binary_sensor.door_garden_contact
    - binary_sensor.door_main_contact

internal_doors:
  entities:
    - binary_sensor.door_kitchen_contact
    - binary_sensor.door_laboratory_contact


light_first_floor:
  entities:
    - light.lamp_living_room_sofa_1_light
    - light.lamp_living_room_sofa_2_light
    - light.lamp_living_room_sofa_3_light
    - light.lamp_living_room_sofa_4_light
    - light.lamp_living_room_window_1_light
    - light.lamp_living_room_window_2_light
    - light.lamp_living_room_tv_1_light
    - light.lamp_living_room_tv_2_light
    - light.lamp_living_room_tv_3_light
    - light.lamp_living_room_tv_4_light
    - light.lamp_living_room_tv_5_light
    - light.lamp_living_room_garden_1_light
    - light.lamp_living_room_garden_2_light
    - light.lamp_living_room_garden_3_light
    - light.lamp_living_room_kitchen_light
    - light.lamp_living_room_door_light
    - switch.lamp_laboratory
