mode: yaml
resources:
  - url: /local/community/mini-media-player/mini-media-player-bundle.js?v=1.7.0
    type: module
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.9.3
    type: module
  - url: /local/community/config-template-card/config-template-card.js?v=1.1.2
    type: module
  - url: /local/community/lovelace-text-input-row/lovelace-text-input-row.js?v=0.0.8
    type: js
