- alias: Restart HA
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: time
    weekday:
    - sun
    - wed
    - fri
  action:
    - service: notify.AURELIO
      data:
        message: 'Auto-Reboot HomeAssistan'
    - service: homeassistant.restart
