##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'People Greeting'

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          "outro conteudo de teste personalizado"
        call_responsibilities: 1
        call_no_announcement: 0
        call_garage_check: 1
        call_window_check: 1
