esphome:
  name: espcamtest
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: "$ssid_ap"
    password: !secret AP_mode_pass

captive_portal:

logger:
  baud_rate: 0

# Enable Home Assistant API//
api:

ota:
  password: !secret ota_pass

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]

  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  name: esp_cam02
  idle_framerate: 0.1fps


output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

binary_sensor:
  - platform: status
    name: "ESP32Cam status"
sensor:
  - platform: wifi_signal
    name: "ESP32Cam WiFi Signal Sensor"
    update_interval: 60s
  - platform: dht
    pin: GPIO16
    temperature:
      name: "ESP32Cam Temperature"
    humidity:
      name: "ESP32Cam Humidity"
    update_interval: 60s
light:
  - platform: binary
    output: gpio_4
    name: ESP32Cam light
