substitutions:
  hostname: "Switch-Two-Gang_01"
  ssid_ap: "Switch_Two_Gang_01"
  versao: "1.0"

esphome:
  name: switch_two_gang
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: "$ssid_ap"
    password: !secret AP_mode_pass

captive_portal:

logger:
  baud_rate: 0

# Enable Home Assistant API//
api:

ota:
  password: !secret ota_pass

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$hostname touch 1"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "$hostname touch 2"
    id: button_2
    on_press:
      then:
        - switch.toggle: switch_1
  - platform: status
    name: "$hostname Status"

switch:
  - platform: gpio
    name: "$hostname button 1"
    pin: GPIO12
  - platform: gpio
    name: "$hostname button 2"
    pin: GPIO5
    id: switch_1

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "$hostname LED"
    output: blue_led
