######################################################################################################
###Script to actually send notifications to the ChromeCast Audios during normal hours and only when we are home! Call like this:
  # action:
    # service: script.speech_engine
    # speech_message:
# # @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
######################################################################################################


speech_processing:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'polly/lastmsg'
        payload: "{{ now().strftime('%-I') }}:{{ now().strftime('%M') }} {{ now().strftime('%p') }}. {{ speech_message | truncate(220)}}"
        retain: true
    # - service: notify.AURELIO
    #   data_template:
    #     message: "{{ now().strftime('%-I') }}:{{ now().strftime('%M') }} {{ now().strftime('%p') }}. {{ speech_message | truncate(220)}}"
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: group.family
              state: 'home'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'on'
        # - condition: or
        #   conditions:
        #     - condition: and
        #       conditions:
        #         - condition: time
        #           after: '08:00:00'
        #           before: '23:00:00'
        - condition: state
          entity_id: input_boolean.speech_notifications
          state: 'on'

    # - service: media_player.volume_set
    #   data_template:
    #    entity_id: >
    #      {{ media_player }}
    #    volume_level: >-
    #      {% if now().strftime('%H')|int < 12 and now().strftime('%H')|int > 6 %}
    #        0.3
    #      {% elif now().strftime('%H')|int > 12 and now().strftime('%H')|int < 20 %}
    #        0.5
    #      {% else %}
    #        0.3
    #      {% endif %}
    # - delay: 1
    - service: notify.alexa_media
      data_template:
        target: >
          {{ media_player }}
        data:
          type: announce
        message: >
          {{ speech_message }}
